name = "junkboats-collector"
main = "src/index.ts"
compatibility_date = "2023-02-17"
kv_namespaces = [
  { binding = "POST_DB", id = "edcc7133b10b4bc3bc289a9f18d5c539", preview_id = "7a5a1fe9205449649c3f738508183012" }
]